version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: docchat
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/docchat
      - GEMINI_API_KEY=AIzaSyD9qI2BJkKsRdw9ESURlj5eqQVKV_LxfdM
      - SECRET_KEY=2bb4b80b713bd4df8ee86423e40df31c56f2dd8e0e4a36efc877e731129e9253
      - MODEL_NAME=gemini-flash-latest
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
